export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RECEIVE_AUTHED_PLANTS = 'RECEIVE_AUTHED_PLANTS';
export const RECEIVE_LIKED_PLANTS = 'RECEIVE_LIKED_PLANTS';
export const OBTAINED_EMAIL = 'OBTAINED_EMAIL';